/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.ica.tests;

import org.junit.jupiter.api.Test;

public class StoreSelectorTest extends TestBase {

    @Test public void testSomeLibraryMethod() {
        page.homePage
                .clickOnHandlaOnlineLink();
    }
}
